# Taken from: https://github.com/houseabsolute/ubi
name: Tests and release
on: 
  push:
    tags:
      - '*'
env:
  CRATE_NAME: dotfiles
  RUST_BACKTRACE: 1
jobs:
  test:
    permissions: 
      contents: write
    name: ${{ matrix.platform.os_name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          # - os_name: Linux-x86_64
          #   os: ubuntu-20.04
          #   target: x86_64-unknown-linux-musl
          #   bin: dotfiles
          #   name: dotfiles-Linux-x86_64-musl.tar.gz
          - os_name: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: dotfiles.exe
            name: dotfiles-Windows-x86_64.zip
          #   - os_name: macOS-aarch64
          #     os: macOS-latest
          #     target: aarch64-apple-darwin
          #     bin: dotfiles
          #     name: dotfiles-Darwin-aarch64.tar.gz
          #     skip_tests: true
        toolchain:
          - stable
          # - beta
          # - nightly
    steps:
      - uses: actions/checkout@v4
        with: 
          persist-credentials: false
      - uses: actions/create-github-app-token@v2
        id: get-dotfiles-github-app-token
        with:
          app-id: ${{ vars.AUTHENTICATION_APP_ID }}
          private-key: ${{ secrets.AUTHENTICATION_PRIVATE_KEY }}
          repositories: common
      - uses: actions/create-github-app-token@v2
        id: get-other-github-app-token
        with:
          app-id: ${{ vars.AUTHENTICATION_APP_ID }}
          private-key: ${{ secrets.AUTHENTICATION_PRIVATE_KEY }}
          owner: RobinCombrink
          repositories: GithubAuthentication
      - name: Setup Git
        run: |
          git config --global url."https://x-access-token:${{ steps.get-dotfiles-github-app-token.outputs.token }}@github.com/DotfilesConfigurator".insteadOf https://github.com/DotfilesConfigurator
          git config --global url."https://x-access-token:${{ steps.get-other-github-app-token.outputs.token }}@github.com/RobinCombrink".insteadOf https://github.com/RobinCombrink
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          key: "v2"
      - name: Install musl-tools on Linux
        if: contains(matrix.platform.name, 'musl')
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        env:
            CARGO_NET_GIT_FETCH_WITH_CLI: true
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
          strip: true
      - name: Run tests
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "test"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args: "--locked --release"
        if: ${{ !matrix.platform.skip_tests }}
      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
            7z a ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          else
            tar czvf ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          fi
          cd -
        if: |
          matrix.toolchain == 'stable' && startsWith( github.ref, 'refs/tags/' )
      - name: Publish release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotfiles-${{ matrix.platform.os_name }}
          path: "target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}"
        if: matrix.toolchain == 'stable' && startsWith( github.ref, 'refs/tags/' )
      - name: Generate SHA-256
        run: shasum -a 256 ${{ matrix.platform.name }}
        if: |
          matrix.toolchain == 'stable' &&
          matrix.platform.os == 'macOS-latest' &&
          ( startsWith( github.ref, 'refs/tags/' ) ||
            github.ref == 'refs/tags/test-release' )
      - name: Publish GitHub release
        if: matrix.toolchain == 'stable' && startsWith( github.ref, 'refs/tags/' )
        uses: softprops/action-gh-release@v3.0.1
        with:
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "target/${{ matrix.platform.target }}/release/dotfiles*\nschema/configuration_schema.json"
          generate_release_notes: true